### PR TITLE
Tweaks for iframed demo UI on product page

### PR DESCRIPTION
**Pull request by louh**

### CODE REVIEW

**Comment by bcamper** [comment]
@louh where is this iframed on the Tangram product page? doesn't hurt nonetheless

**Comment by louh** [comment]
ah... it's not on Tangram, it's the fourth option on the Vector Tiles page. 
https://mapzen.com/projects/vector-tiles

**Comment by bcamper** [comment]
oh I see. We could just point that page at the same carousel page as the main Tangram page (which also has a Tron tab :)

**Comment by louh** [comment]
Oh, that's a good point...

**Comment by louh** [comment]
This will take care of that
https://github.com/mapzen/blog/pull/242

**Comment by bcamper** [comment]
Thanks!

**Pull request closed without merging**
